version: '3'

services:
  flask-backend:
    build: ./flask-backend
    ports:
      - "5000:5000"
    depends_on:
      - mongodb-database
    environment:
      - MONGO_URI=mongodb://mongodb-database:27017

  streamlit-frontend:
    build: ./streamlit-frontend
    ports:
      - "8080:8080"
    depends_on:
      - flask-backend
      - mongodb-database

  mongodb-database:
    image: mongo
    ports:
      - "27017:27017"
